package vn.edu.hust.soict.soe.assetmanagement.handover.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.UUID;

/**
 * ==============================================================================
 * DTO: CreateHandoverRequest
 * ==============================================================================
 * PURPOSE:
 *   Represents the JSON request body sent by the client when submitting a
 *   new asset handover request via POST /api/handovers.
 *
 *   This DTO is the ONLY way data enters the handover creation flow. The JPA
 *   entity (HandoverRequest.java) is NEVER exposed directly to the API layer.
 *
 * VALIDATION:
 *   All fields annotated with Bean Validation constraints (JSR-380).
 *   If any constraint fails, Spring throws MethodArgumentNotValidException,
 *   which GlobalExceptionHandler converts to a 400 response with field errors.
 *
 * FIELDS INTENTIONALLY EXCLUDED:
 *   - id          → generated by DB (UUID strategy)
 *   - requestCode → generated by HandoverService (e.g. "BG-2025-001")
 *   - status      → always starts as DRAFT, set by service
 *   - initiatedBy → extracted from JWT SecurityContext in HandoverService,
 *                   never trusted from client input (security rule)
 *   - All approval/confirmation/rejection fields → set by service at each step
 *   - documentRef, documentSigned → managed by HandoverDocumentService
 *
 * USAGE:
 *   HandoverController.createHandover(@Valid @RequestBody CreateHandoverRequest req)
 *   → validated automatically before reaching the controller method body
 * ==============================================================================
 */
@Getter
@Setter
@NoArgsConstructor
public class CreateHandoverRequest {

    /**
     * UUID of the FixedAsset being transferred.
     * Must reference a real asset in the `assets` table.
     * Validated at service layer: asset must exist and be IN_USE or IDLE.
     */
    @NotNull(message = "Asset ID không được để trống")
    private UUID assetId;

    /**
     * UUID of the managing unit that currently holds the asset (sender).
     * Must match the asset's current managingUnitId — validated in service.
     */
    @NotNull(message = "Đơn vị bàn giao không được để trống")
    private UUID fromUnitId;

    /**
     * UUID of the managing unit that will receive the asset (receiver).
     * Must differ from fromUnitId — validated in service.
     */
    @NotNull(message = "Đơn vị tiếp nhận không được để trống")
    private UUID toUnitId;

    /**
     * Business justification for why the asset is being transferred.
     * Required; max 2000 characters to avoid abuse.
     */
    @NotBlank(message = "Lý do bàn giao không được để trống")
    @Size(max = 2000, message = "Lý do không được vượt quá 2000 ký tự")
    private String reason;

    /**
     * Planned or actual date of physical handover.
     * Must not be in the future (cannot pre-date a handover that hasn't happened).
     * Optional — can be filled in at confirmation step if not known upfront.
     */
    @PastOrPresent(message = "Ngày bàn giao không thể ở tương lai")
    private LocalDate handoverDate;

    /**
     * Physical condition of the asset at time of handover.
     * Expected values: "GOOD", "FAIR", "POOR"
     * Not enforced as an enum here to allow frontend flexibility; validated in service.
     */
    @Size(max = 50, message = "Tình trạng tài sản tối đa 50 ký tự")
    private String assetCondition;

    /**
     * Any free-text additional notes from the person initiating the request.
     * Optional.
     */
    @Size(max = 1000, message = "Ghi chú không được vượt quá 1000 ký tự")
    private String notes;
}