package vn.edu.hust.soict.soe.assetmanagement.handover.entity;

import jakarta.persistence.*;
import lombok.*;
import vn.edu.hust.soict.soe.assetmanagement.common.BaseEntity;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * ==============================================================================
 * ENTITY: HandoverRequest
 * ==============================================================================
 * PURPOSE:
 *   JPA entity that maps directly to the `handover_requests` table defined in
 *   V4__create_handover_liquidation.sql. Represents one complete asset-transfer
 *   workflow from initiation through final completion or rejection.
 *
 * EXTENDS BaseEntity:
 *   This entity DOES extend BaseEntity, which provides:
 *     - created_at  (auto-set on INSERT by JPA Auditing)
 *     - updated_at  (auto-set on INSERT and UPDATE by JPA Auditing)
 *     - created_by  (auto-set to current username from SecurityContext)
 *   This is correct per the schema — handover_requests IS an updatable table
 *   (unlike append-only tables like asset_history or audit_logs).
 *
 * WORKFLOW STATES (see HandoverStatus.java for full diagram):
 *   DRAFT → PENDING_APPROVAL → APPROVED → CONFIRMED → COMPLETED
 *                                     └─────────────────────────► REJECTED
 *
 * FIELD-TO-COLUMN MAPPING (exact match to V4 SQL):
 *   Every @Column name matches the snake_case SQL column name.
 *   Every length constraint matches the VARCHAR(n) in SQL.
 *
 * KEY BUSINESS RULES ENFORCED (at service layer, documented here for clarity):
 *   1. initiated_by != dept_approved_by  (separation of duties — HL-01)
 *   2. Only one active (non-REJECTED, non-COMPLETED) request per asset at a time
 *   3. from_unit_id != to_unit_id  (cannot hand over to the same unit)
 *
 * INTEGRATION:
 *   - HandoverService reads and writes this entity
 *   - HandoverDto is the external-facing representation (entity never leaves service layer)
 *   - On APPROVED: FixedAssetService.updateAssetStatusAndUnit() is called
 *   - On any state change: AuditLogService.log() is called
 * ==============================================================================
 */
@Entity
@Table(
    name = "handover_requests",
    indexes = {
        @Index(name = "idx_handover_code",      columnList = "request_code"),
        @Index(name = "idx_handover_asset",     columnList = "asset_id"),
        @Index(name = "idx_handover_status",    columnList = "status"),
        @Index(name = "idx_handover_from_unit", columnList = "from_unit_id"),
        @Index(name = "idx_handover_to_unit",   columnList = "to_unit_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = true) // Required when extending BaseEntity
public class HandoverRequest extends BaseEntity {

    // ── PRIMARY KEY ───────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    // ── IDENTITY ──────────────────────────────────────────────────────────

    /**
     * Human-readable business code, e.g. "BG-2024-001".
     * Generated by HandoverService before saving. Must be unique.
     * Maps to: request_code VARCHAR(50) NOT NULL UNIQUE
     */
    @Column(name = "request_code", nullable = false, unique = true, length = 50)
    private String requestCode;

    /**
     * The UUID of the FixedAsset being transferred.
     * Maps to: asset_id UUID NOT NULL REFERENCES assets(id)
     * Note: We store the UUID directly (not a @ManyToOne) to avoid circular
     *       dependency between asset and handover modules.
     */
    @Column(name = "asset_id", nullable = false)
    private UUID assetId;

    // ── PARTIES INVOLVED ──────────────────────────────────────────────────

    /**
     * UUID of the managing unit currently holding the asset (sender).
     * Maps to: from_unit_id UUID NOT NULL REFERENCES managing_units(id)
     */
    @Column(name = "from_unit_id", nullable = false)
    private UUID fromUnitId;

    /**
     * UUID of the managing unit that will receive the asset (receiver).
     * Maps to: to_unit_id UUID NOT NULL REFERENCES managing_units(id)
     */
    @Column(name = "to_unit_id", nullable = false)
    private UUID toUnitId;

    /**
     * Username of the person who created this request.
     * Maps to: initiated_by VARCHAR(100) NOT NULL
     * Business rule: Must differ from dept_approved_by (separation of duties).
     */
    @Column(name = "initiated_by", nullable = false, length = 100)
    private String initiatedBy;

    // ── WORKFLOW STATUS ───────────────────────────────────────────────────

    /**
     * Current state in the approval workflow.
     * Stored as String (EnumType.STRING) to match VARCHAR(30) in DB.
     * Maps to: status VARCHAR(30) NOT NULL DEFAULT 'DRAFT'
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private HandoverStatus status = HandoverStatus.DRAFT;

    // ── JUSTIFICATION & CONTEXT ───────────────────────────────────────────

    /**
     * Business justification for the transfer (mandatory, free text).
     * Maps to: reason TEXT NOT NULL
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String reason;

    /**
     * Planned or actual date of physical handover.
     * Maps to: handover_date DATE
     */
    @Column(name = "handover_date")
    private LocalDate handoverDate;

    /**
     * Condition of the asset at time of handover: GOOD | FAIR | POOR
     * Maps to: asset_condition VARCHAR(50)
     */
    @Column(name = "asset_condition", length = 50)
    private String assetCondition;

    /**
     * Any additional free-text notes from the initiator.
     * Maps to: notes TEXT
     */
    @Column(columnDefinition = "TEXT")
    private String notes;

    // ── STEP 1: DEPARTMENT HEAD APPROVAL ─────────────────────────────────

    /**
     * Username of the person who approved at Step 1.
     * Maps to: dept_approved_by VARCHAR(100)
     * Business rule: Must NOT equal initiatedBy.
     */
    @Column(name = "dept_approved_by", length = 100)
    private String deptApprovedBy;

    /**
     * Timestamp when Step 1 approval was granted.
     * Maps to: dept_approved_at TIMESTAMP
     */
    @Column(name = "dept_approved_at")
    private LocalDateTime deptApprovedAt;

    /**
     * Optional notes left by the approver at Step 1.
     * Maps to: dept_approval_notes TEXT
     */
    @Column(name = "dept_approval_notes", columnDefinition = "TEXT")
    private String deptApprovalNotes;

    // ── STEP 2: RECEIVING UNIT CONFIRMATION ───────────────────────────────

    /**
     * Username of the person from the receiving unit who confirmed receipt.
     * Maps to: confirmed_by VARCHAR(100)
     */
    @Column(name = "confirmed_by", length = 100)
    private String confirmedBy;

    /**
     * Timestamp when the receiving unit confirmed receipt.
     * Maps to: confirmed_at TIMESTAMP
     */
    @Column(name = "confirmed_at")
    private LocalDateTime confirmedAt;

    /**
     * Optional notes from the receiving unit during confirmation.
     * Maps to: confirmation_notes TEXT
     */
    @Column(name = "confirmation_notes", columnDefinition = "TEXT")
    private String confirmationNotes;

    // ── STEP 3: FINAL RECORD COMPLETION ───────────────────────────────────

    /**
     * Username of the person who marked this request as COMPLETED.
     * Maps to: completed_by VARCHAR(100)
     */
    @Column(name = "completed_by", length = 100)
    private String completedBy;

    /**
     * Timestamp when the request was marked COMPLETED.
     * Maps to: completed_at TIMESTAMP
     */
    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    // ── REJECTION (ANY STEP) ──────────────────────────────────────────────

    /**
     * Username of the person who rejected the request.
     * Maps to: rejected_by VARCHAR(100)
     */
    @Column(name = "rejected_by", length = 100)
    private String rejectedBy;

    /**
     * Timestamp when the rejection occurred.
     * Maps to: rejected_at TIMESTAMP
     */
    @Column(name = "rejected_at")
    private LocalDateTime rejectedAt;

    /**
     * Mandatory reason for rejection, required when setting status to REJECTED.
     * Maps to: rejection_reason TEXT
     */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;

    // ── HL-03: GENERATED DOCUMENT ─────────────────────────────────────────

    /**
     * Reference number of the generated "Biên bản bàn giao" document.
     * Populated by HandoverDocumentService once the document is generated.
     * Maps to: document_ref VARCHAR(255)
     */
    @Column(name = "document_ref", length = 255)
    private String documentRef;

    /**
     * Timestamp when the formal handover document was generated.
     * Maps to: document_generated_at TIMESTAMP
     */
    @Column(name = "document_generated_at")
    private LocalDateTime documentGeneratedAt;

    /**
     * Whether the handover document has been digitally or physically signed.
     * Maps to: document_signed BOOLEAN NOT NULL DEFAULT FALSE
     */
    @Column(name = "document_signed", nullable = false)
    @Builder.Default
    private Boolean documentSigned = false;
}