spring:
  application:
    name: soe-asset-management
  profiles:
    active: dev

server:
  port: 8080

jwt:
  # 256-bit Hex key
  secret: your_secret_key_here
  # 8 hours expiration
  expiration-ms: 28800000