package vn.edu.hust.soict.soe.assetmanagement.liquidation.dto;

import jakarta.validation.constraints.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * ==============================================================================
 * DTO: CreateLiquidationRequest
 * ==============================================================================
 * PURPOSE:
 *   Represents the JSON request body sent by the frontend when an Asset Manager
 *   submits a new liquidation request via POST /api/liquidations.
 *
 *   This is the ONLY entry point for new liquidation data. The JPA entity
 *   (LiquidationRequest.java) is NEVER directly exposed to the API layer.
 *
 * VALIDATION:
 *   All constraints use JSR-380 Bean Validation annotations. If any constraint
 *   fails, Spring throws MethodArgumentNotValidException before the controller
 *   method body executes. GlobalExceptionHandler converts this to a 400 response
 *   with a field → Vietnamese error message map.
 *
 * FIELDS INTENTIONALLY EXCLUDED (set server-side, never from client input):
 *   - id              → generated by DB (gen_random_uuid())
 *   - requestCode     → generated by LiquidationService ("TL-2025-0001")
 *   - status          → always starts as DRAFT, set by service
 *   - initiatedBy     → always read from JWT token in the controller (security rule:
 *                       never trust the client for identity)
 *   - managerApprovedBy, directorApprovedBy, etc. → set at each workflow step
 *   - completedAt, rejectedAt, etc.               → set by service at each step
 *   - documentRef, documentSigned                 → managed on completion
 *   - finalDisposalValue                          → provided at completion, not creation
 *
 * KEY DIFFERENCE FROM CreateHandoverRequest:
 *   Liquidation requires MORE mandatory fields at creation time (per HL-02):
 *   - justification (why liquidate)
 *   - assetCondition (GOOD/FAIR/POOR/DAMAGED — DAMAGED is exclusive to liquidation)
 *   - disposalMethod (AUCTION/SCRAP/DONATION)
 *   These are mandatory because approvers need this information to evaluate the request.
 *
 * USAGE:
 *   LiquidationController.createLiquidation(@Valid @RequestBody CreateLiquidationRequest req)
 * ==============================================================================
 */
@Getter
@Setter
@NoArgsConstructor
public class CreateLiquidationRequest {

    /**
     * UUID of the FixedAsset to be liquidated.
     * Must reference a real, non-LIQUIDATED asset.
     * Validated at service layer: asset must exist and must not already be LIQUIDATED.
     */
    @NotNull(message = "Asset ID không được để trống")
    private UUID assetId;

    /**
     * UUID of the managing unit requesting the liquidation.
     * Should match the asset's current managing unit.
     * Validated at service layer.
     */
    @NotNull(message = "Đơn vị yêu cầu không được để trống")
    private UUID requestingUnitId;

    /**
     * Detailed justification for why this asset must be liquidated.
     * Required by HL-02. The approver needs a clear rationale to evaluate the request.
     * Max 2000 characters to prevent abuse.
     */
    @NotBlank(message = "Lý do thanh lý không được để trống")
    @Size(max = 2000, message = "Lý do không được vượt quá 2000 ký tự")
    private String justification;

    /**
     * Physical condition of the asset at the time of this request.
     * Allowed values: GOOD | FAIR | POOR | DAMAGED
     * Note that DAMAGED is available here but NOT in the handover module —
     * a damaged asset can be liquidated but not transferred to another unit.
     * Required by HL-02.
     */
    @NotBlank(message = "Tình trạng tài sản không được để trống")
    @Size(max = 50, message = "Tình trạng tài sản tối đa 50 ký tự")
    private String assetCondition;

    /**
     * Estimated current market value of the asset, in VND.
     * Optional — approvers use this to decide on the disposal method.
     * Must be >= 0 if provided.
     */
    @DecimalMin(value = "0.0", inclusive = true, message = "Giá trị thị trường phải >= 0")
    private BigDecimal currentMarketValue;

    /**
     * The planned disposal method for this asset.
     * Allowed values: AUCTION | SCRAP | DONATION
     * Required by HL-02 — the initiator must propose a disposal approach.
     */
    @NotBlank(message = "Phương thức thanh lý không được để trống")
    @Size(max = 30, message = "Phương thức thanh lý tối đa 30 ký tự")
    private String disposalMethod;

    /**
     * Optional additional notes about the planned disposal.
     * For example: "Sẽ đấu giá tại Trung tâm đấu giá tỉnh vào Q3/2025"
     */
    @Size(max = 1000, message = "Ghi chú không được vượt quá 1000 ký tự")
    private String disposalNotes;
}