package vn.edu.hust.soict.soe.assetmanagement.liquidation.entity;

import jakarta.persistence.*;
import lombok.*;
import vn.edu.hust.soict.soe.assetmanagement.common.BaseEntity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * ==============================================================================
 * ENTITY: LiquidationRequest
 * ==============================================================================
 * PURPOSE:
 *   JPA entity that maps directly to the `liquidation_requests` table defined in
 *   V4__create_handover_liquidation.sql. Represents one complete asset-disposal
 *   workflow from initiation through final completion or rejection.
 *
 * EXTENDS BaseEntity:
 *   This entity DOES extend BaseEntity, which provides:
 *     - created_at  (auto-set on INSERT by JPA Auditing — AuditConfig.java)
 *     - updated_at  (auto-set on INSERT and UPDATE by JPA Auditing)
 *     - created_by  (auto-set to the current username from SecurityContext)
 *   This is correct because liquidation_requests IS an updatable operational table,
 *   unlike append-only tables (asset_history, stock_transactions, audit_logs) which
 *   must NOT extend BaseEntity.
 *
 * WORKFLOW (two approval steps — differs from handover's single step):
 *   DRAFT → PENDING_MANAGER → PENDING_DIRECTOR → APPROVED → COMPLETED
 *                   └──────────────────────────────────────► REJECTED
 *
 * CRITICAL DISTINCTION FROM HANDOVER:
 *   The asset table is NOT touched during approval steps. The asset is only
 *   set to LIQUIDATED when the request reaches COMPLETED. This means there
 *   is no "asset rollback" needed on rejection, unlike the handover workflow
 *   where the asset is marked TRANSFERRED on approval and must be rolled back
 *   if the request is later rejected.
 *
 * FIELD-TO-COLUMN MAPPING (exact match to V4 SQL):
 *   Every @Column name matches the snake_case SQL column name exactly.
 *   Every length matches the VARCHAR(n) / NUMERIC(p,s) in the migration.
 *
 * KEY BUSINESS RULES (enforced in LiquidationService, documented here):
 *   1. initiated_by != manager_approved_by  (separation of duties — BR-02)
 *   2. Only one active (non-REJECTED, non-COMPLETED) request per asset at a time
 *   3. Once COMPLETED: asset becomes permanently read-only (BR-05)
 *   4. justification, asset_condition, disposal_method are all mandatory
 *
 * INTEGRATION:
 *   - LiquidationService reads and writes this entity
 *   - LiquidationDto is the safe API-facing representation
 *   - On COMPLETED: FixedAssetService.updateAssetStatus() marks asset LIQUIDATED
 *   - On any state change: AuditLogService.log() writes to audit_logs
 * ==============================================================================
 */
@Entity
@Table(
    name = "liquidation_requests",
    indexes = {
        @Index(name = "idx_liquidation_code",   columnList = "request_code"),
        @Index(name = "idx_liquidation_asset",  columnList = "asset_id"),
        @Index(name = "idx_liquidation_status", columnList = "status"),
        @Index(name = "idx_liquidation_unit",   columnList = "requesting_unit_id")
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@EqualsAndHashCode(callSuper = true) // Required when extending BaseEntity
public class LiquidationRequest extends BaseEntity {

    // ── PRIMARY KEY ───────────────────────────────────────────────────────

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    // ── IDENTITY ──────────────────────────────────────────────────────────

    /**
     * Human-readable business code, e.g. "TL-2024-001".
     * Generated by LiquidationService.generateRequestCode() before first save.
     * "TL" = Thanh Lý (Liquidation in Vietnamese).
     * Must be unique across all liquidation requests.
     * Maps to: request_code VARCHAR(50) NOT NULL UNIQUE
     */
    @Column(name = "request_code", nullable = false, unique = true, length = 50)
    private String requestCode;

    /**
     * UUID of the FixedAsset being liquidated.
     * Stored as a plain UUID (not a @ManyToOne) to avoid circular dependency
     * between the liquidation and asset packages. The service calls
     * FixedAssetService to interact with the asset at completion time.
     * Maps to: asset_id UUID NOT NULL REFERENCES assets(id)
     */
    @Column(name = "asset_id", nullable = false)
    private UUID assetId;

    /**
     * UUID of the managing unit that is requesting the liquidation.
     * This is the unit that currently owns the asset.
     * Maps to: requesting_unit_id UUID NOT NULL REFERENCES managing_units(id)
     */
    @Column(name = "requesting_unit_id", nullable = false)
    private UUID requestingUnitId;

    /**
     * Username of the person who created this liquidation request.
     * Never taken from the request body — always read from the JWT token
     * in the controller to prevent identity spoofing.
     * Business rule (BR-02): must differ from manager_approved_by.
     * Maps to: initiated_by VARCHAR(100) NOT NULL
     */
    @Column(name = "initiated_by", nullable = false, length = 100)
    private String initiatedBy;

    // ── WORKFLOW STATUS ───────────────────────────────────────────────────

    /**
     * Current state of the two-step approval workflow.
     * Stored as a String (EnumType.STRING) to match VARCHAR(30) in DB.
     * Always starts at DRAFT when a request is created.
     * Maps to: status VARCHAR(30) NOT NULL DEFAULT 'DRAFT'
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private LiquidationStatus status = LiquidationStatus.DRAFT;

    // ── HL-02 JUSTIFICATION FIELDS (all mandatory per SRS HL-02) ─────────

    /**
     * Detailed business justification for why this asset must be liquidated.
     * Examples: "Máy tính hỏng không thể sửa chữa", "Tài sản hết khấu hao 5 năm".
     * Mandatory per HL-02: the initiator must explain the disposal rationale.
     * Maps to: justification TEXT NOT NULL
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String justification;

    /**
     * Physical condition of the asset at the time of the liquidation request.
     * Allowed values: GOOD | FAIR | POOR | DAMAGED
     * Note: DAMAGED is an extra option not available in the handover module —
     * a liquidation can be triggered specifically because the asset is damaged
     * beyond repair.
     * Mandatory per HL-02.
     * Maps to: asset_condition VARCHAR(50) NOT NULL
     */
    @Column(name = "asset_condition", nullable = false, length = 50)
    private String assetCondition;

    /**
     * The estimated current market value of the asset at request time, in VND.
     * Used by approvers to assess whether auction/scrap/donation is appropriate.
     * Optional — can be null if the market value is unknown or negligible.
     * Maps to: current_market_value NUMERIC(18,2)
     */
    @Column(name = "current_market_value", precision = 18, scale = 2)
    private BigDecimal currentMarketValue;

    /**
     * How the asset will be disposed of after liquidation approval.
     * Allowed values: AUCTION | SCRAP | DONATION
     * Mandatory per HL-02.
     * Maps to: disposal_method VARCHAR(30) NOT NULL
     */
    @Column(name = "disposal_method", nullable = false, length = 30)
    private String disposalMethod;

    /**
     * Free-text notes about the planned disposal process.
     * Optional — used to provide additional context to the approvers.
     * Maps to: disposal_notes TEXT
     */
    @Column(name = "disposal_notes", columnDefinition = "TEXT")
    private String disposalNotes;

    // ── STEP 1: ASSET MANAGER APPROVAL ───────────────────────────────────

    /**
     * Username of the person who approved at Step 1 (manager level).
     * Business rule (BR-02): must NOT equal initiatedBy.
     * Null until Step 1 is acted on.
     * Maps to: manager_approved_by VARCHAR(100)
     */
    @Column(name = "manager_approved_by", length = 100)
    private String managerApprovedBy;

    /**
     * Exact timestamp when Step 1 approval was granted.
     * Used for the audit trail and the printed document.
     * Maps to: manager_approved_at TIMESTAMP
     */
    @Column(name = "manager_approved_at")
    private LocalDateTime managerApprovedAt;

    /**
     * Optional notes left by the Step 1 approver explaining their decision.
     * Maps to: manager_notes TEXT
     */
    @Column(name = "manager_notes", columnDefinition = "TEXT")
    private String managerNotes;

    // ── STEP 2: DIRECTOR/BOARD APPROVAL ──────────────────────────────────

    /**
     * Username of the person who approved at Step 2 (director level).
     * This is the highest-level approval required before an asset can be liquidated.
     * Null until Step 2 is acted on.
     * Maps to: director_approved_by VARCHAR(100)
     */
    @Column(name = "director_approved_by", length = 100)
    private String directorApprovedBy;

    /**
     * Exact timestamp when Step 2 approval was granted.
     * Maps to: director_approved_at TIMESTAMP
     */
    @Column(name = "director_approved_at")
    private LocalDateTime directorApprovedAt;

    /**
     * Optional notes left by the Step 2 approver.
     * Maps to: director_notes TEXT
     */
    @Column(name = "director_notes", columnDefinition = "TEXT")
    private String directorNotes;

    // ── COMPLETION ────────────────────────────────────────────────────────

    /**
     * Username of the person who triggered the final COMPLETED transition.
     * At this point the asset is permanently set to LIQUIDATED (BR-05).
     * Maps to: completed_by VARCHAR(100)
     */
    @Column(name = "completed_by", length = 100)
    private String completedBy;

    /**
     * Timestamp when the liquidation workflow was closed.
     * Maps to: completed_at TIMESTAMP
     */
    @Column(name = "completed_at")
    private LocalDateTime completedAt;

    /**
     * The actual monetary value realised from the disposal (auction/scrap/donation).
     * Set at completion time by the person finalising the record.
     * May differ from currentMarketValue (the estimate) given market conditions.
     * Maps to: final_disposal_value NUMERIC(18,2)
     */
    @Column(name = "final_disposal_value", precision = 18, scale = 2)
    private BigDecimal finalDisposalValue;

    // ── REJECTION (ANY STEP) ──────────────────────────────────────────────

    /**
     * Username of the person who rejected the request (at Step 1 or Step 2).
     * Maps to: rejected_by VARCHAR(100)
     */
    @Column(name = "rejected_by", length = 100)
    private String rejectedBy;

    /**
     * Timestamp when the rejection was recorded.
     * Maps to: rejected_at TIMESTAMP
     */
    @Column(name = "rejected_at")
    private LocalDateTime rejectedAt;

    /**
     * Mandatory explanation for why the request was rejected.
     * LiquidationService validates that this is non-blank before recording a rejection.
     * Maps to: rejection_reason TEXT
     */
    @Column(name = "rejection_reason", columnDefinition = "TEXT")
    private String rejectionReason;

    // ── HL-03: GENERATED DOCUMENT ─────────────────────────────────────────

    /**
     * Reference number of the generated "Biên bản thanh lý tài sản" document.
     * Format: BBTL-YYYY-NNNN (Biên Bản Thanh Lý — matches BR-07 convention
     * where TL-YYYY-NNN is the request code).
     * Set by LiquidationService.completeLiquidation() after document generation.
     * Maps to: document_ref VARCHAR(255)
     */
    @Column(name = "document_ref", length = 255)
    private String documentRef;

    /**
     * Timestamp when the official liquidation document was generated.
     * Maps to: document_generated_at TIMESTAMP
     */
    @Column(name = "document_generated_at")
    private LocalDateTime documentGeneratedAt;

    /**
     * Whether the printed/digital document has been signed by all required parties.
     * Starts as FALSE. Can be updated after physical signing is confirmed.
     * Maps to: document_signed BOOLEAN NOT NULL DEFAULT FALSE
     */
    @Column(name = "document_signed", nullable = false)
    @Builder.Default
    private Boolean documentSigned = false;
}